"""empty message

Revision ID: 54ff1c8622b6
Revises: b392505c596e
Create Date: 2018-11-09 21:38:23.200037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54ff1c8622b6'
down_revision = 'b392505c596e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('desc', sa.String(length=90), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cate_sub', 'cate_main',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'cate_sub', 'category', ['cate_main'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cate_sub', type_='foreignkey')
    op.alter_column('cate_sub', 'cate_main',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_table('category')
    # ### end Alembic commands ###
