"""empty message

Revision ID: 76f4078fc89d
Revises: a01afcda19d0
Create Date: 2018-11-09 21:22:36.193150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f4078fc89d'
down_revision = 'a01afcda19d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cate_main', sa.Integer(), nullable=True),
    sa.Column('cate_sub', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=60), nullable=True),
    sa.Column('item_pic', sa.String(length=60), nullable=True),
    sa.Column('item_desc', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
