"""empty message

Revision ID: b392505c596e
Revises: 76f4078fc89d
Create Date: 2018-11-09 21:31:31.540236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b392505c596e'
down_revision = '76f4078fc89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cate_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cate_main', sa.Integer(), nullable=True),
    sa.Column('cate_sub', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=60), nullable=True),
    sa.Column('item_pic', sa.String(length=60), nullable=True),
    sa.Column('item_desc', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cate_main', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cate_sub', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('item_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60), nullable=True),
    sa.Column('item_pic', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60), nullable=True),
    sa.Column('item_desc', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('cate_sub')
    # ### end Alembic commands ###
