"""empty message

Revision ID: d6c59c5ba920
Revises: 54ff1c8622b6
Create Date: 2018-11-10 15:14:33.805560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c59c5ba920'
down_revision = '54ff1c8622b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('pic', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'pic')
    # ### end Alembic commands ###
